### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by fatseahorse** [classiebit/eventmie#1]
## Version information

 - Laravel: v#.#.#
 - Voyager: v#.#.#
 - PHP: #.#
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description

Random test your demo with admin account.

during creating event, when selecting date/time

the end datetime i selected start time 14 Oct 2019 01:05:40 and end time 17 Oct 2019 23:59:50

even if the start end date is correct, it still does not pass through the "date earlier" validation.

please check

**Comment by classiebit** [comment]
Hello,

Nothing found wrong, we've tested and created a test event with the date you mentioned, and it's working good.

See the screenshots - 

1. [https://prnt.sc/ph985h](https://prnt.sc/ph985h)
2. [https://prnt.sc/ph9890](https://prnt.sc/ph9890)

Please add some screenshot from your end if still any issues.


Thank you

**Comment by classiebit** [comment]
Closing the issue due to no further response.
