### ISSUE TITLE
[BUG] It's not possible publish event on edit.

### ISSUE THREAD

**Issue by landlogicit** [classiebit/eventmie#2]
- Laravel: v5.8.*
 - PHP: 7.1
 - Database: [MySQL] [5.7]

## Description

It's not possible publish event on edit.

## Steps To Reproduce
1. Go to '/myevents/manage/nameofevent'
2. Time and date field not get data on insert

**Comment by classiebit** [comment]
Issue resolved in eventmie-pro v1.1.0
