### ISSUE TITLE
Demo Broken... does your app actually work?

### ISSUE THREAD

**Issue by Jossnaz** [classiebit/eventmie#3]
https://drive.google.com/file/d/12VJR2dri7J6bhJm9rLfgGWgqLPUjLGli/view

**Comment by classiebit** [comment]
Hi, please have a look at the pro version - https://eventmie-pro.classiebit.com/. As due to COVID-19, we're working from home, and we're only focusing on the Premium products. Everything is running fine on the pro version. Have a look. And we'll release the bugs in Lite version after COVID-19 ends.

**Comment by Jossnaz** [comment]
is there an admin login in the demo?

**Comment by mkopcic** [comment]
Demo only on their website, this piece of software is broken and they have 0 support or manner.

**Comment by classiebit** [comment]
@Jossnaz for the Admin Panel, please visit http://eventmie.classiebit.com/ and login as -

admin@admin.com / password 

and you'll find the link to Admin Panel in the header.

**Comment by classiebit** [comment]
@mkopcic Please try now, if things still not work, let us know by email.

Hi,

Very sorry for the inconvenience. We usually respond within 24-48 business hours and sometimes it gets delayed as we're currently working with limited resources.

But as COVID Vaccine arrived, things will get back to normal very soon. Hence, apologies for now.

**Comment by mkopcic** [comment]
Thanks for reply i managed to install it. Working with php 7.3.
