### ISSUE TITLE
Issue when using composer require classiebit/eventmie

### ISSUE THREAD

**Issue by sebSpencer** [classiebit/eventmie#4]
Deprecation Notice: Class Classiebit\Eventmie\Http\Controllers\MybookingsController located in ./vendor/classiebit/eventmie/src/Http/Controllers/MyBookingsController.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201

Hi I am looking to get a local version up and running to do some testing, I am thinking we maybe able to use this for a project we are building.

**Comment by MarijanKopcic** [comment]
Same here. Can't install via composer.
![image](https://user-images.githubusercontent.com/77619844/105373210-ba4b7a80-5c06-11eb-8bf6-453793b39124.png)

**Comment by mkopcic** [comment]
Still same issue, even submited ticket on website. Your software is not working.

**Comment by classiebit** [comment]
Issue resolved. Please try now.

**Comment by mkopcic** [comment]
Works well with PHP 7.3 only.

**Comment by classiebit** [comment]
Yes, because Laravel 8 requires PHP 7.3. While, if you wanna use older than PHP 7.3, then install it with Laravel 7 or below.
